universe = vanilla

# Where should the output/error be saved
log = logs/cuda_job.log
output = logs/cuda_job.out
error = logs/cuda_job.err

# Specify the executable and arguments
executable = kmeans_cuda
arguments = test_files/input2D.inp 6 300 10 0.0001 test_files/output2d_cuda.txt

# Request GPU resources
request_gpus = 1

# Exclude specific machines
requirements = (Machine != "node126.di.rm1")

# Specify any environment setup if needed
getenv = True

# Queue the job
queue
